Task: Finalize base configuration of retrofit. (#9)
* chore: initial setup for networkingModule.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: added sample api implementation.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: minor config update to build type, debug.
added build type, staging, for learning purposes.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: added & configured chucker dependency.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: added showToast and showing of version info in SettingsScreen.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* Final Base Retrofit Configuration (#8)

* chore: successful network call.
error: Caused by: java.lang.IllegalArgumentException: Could not locate RequestBody converter for class kib.project.data.api.models.requests.SampleLoginUserRequest.
Tried:
* retrofit2.BuiltInConverters
* retrofit2.OptionalConverterFactory

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: added gson dependencies to module, app. configured sealed class, NetworkCallResult.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: tested open/free api, api.themoviedb.org/3/.

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

* chore: added class AuthInterceptor()

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

---------

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>

---------

Signed-off-by: kibdev <31766430+kibmuikia@users.noreply.github.com>